name = "Polyhedra"
uuid = "67491407-f73d-577b-9b50-8179a7c68029"
repo = "https://github.com/JuliaPolyhedra/Polyhedra.jl.git"
version = "0.5.2"

[deps]
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ParameterJuMP = "774612a8-9878-5177-865a-ca53ae2495f9"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
GeometryTypes = "≥ 0.4"
JuMP = "0.19"
RecipesBase = "≥ 0.2"
StaticArrays = "≥ 0.5"
julia = "1"
ParameterJuMP = "0.1.1"

[extras]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Combinatorics", "GLPK", "Test"]
